version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mordecai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mordecai-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/mordecai?schema=public
      NODE_ENV: production
      JWT_SECRET: your-production-jwt-secret
    depends_on:
      - postgres
    networks:
      - mordecai-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mordecai-network
    environment:
      REACT_APP_API_URL: http://localhost:5000/api

volumes:
  postgres_data:

networks:
  mordecai-network:
    driver: bridge